version: '3.8'
services:
  comfyui:
    image: code0100fun/comfyui-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui
    ports:
      - '8188:8188'
    volumes:
      - ./extra_model_paths.yaml:/home/comfyui/ComfyUI/extra_model_paths.yaml:ro'
      - '/mnt/ai/comfyui/output:/home/comfyui/output:rw'
      - '/mnt/ai/models:/mnt/ai/models:ro'
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            -
              driver: nvidia
              count: 1
              capabilities:
                - gpu
